'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar de My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VACIO")>  _
        Public Property ServDatos0() As String
            Get
                Return CType(Me("ServDatos0"),String)
            End Get
            Set
                Me("ServDatos0") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VACIO")>  _
        Public Property ServDatos1() As String
            Get
                Return CType(Me("ServDatos1"),String)
            End Get
            Set
                Me("ServDatos1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VACIO")>  _
        Public Property ServDatos2() As String
            Get
                Return CType(Me("ServDatos2"),String)
            End Get
            Set
                Me("ServDatos2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VACIO")>  _
        Public Property ServDatos3() As String
            Get
                Return CType(Me("ServDatos3"),String)
            End Get
            Set
                Me("ServDatos3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VACIO")>  _
        Public Property ServDatos4() As String
            Get
                Return CType(Me("ServDatos4"),String)
            End Get
            Set
                Me("ServDatos4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VACIO")>  _
        Public Property ServDatos5() As String
            Get
                Return CType(Me("ServDatos5"),String)
            End Get
            Set
                Me("ServDatos5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VACIO")>  _
        Public Property ServDatos6() As String
            Get
                Return CType(Me("ServDatos6"),String)
            End Get
            Set
                Me("ServDatos6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VACIO")>  _
        Public Property ServDatos7() As String
            Get
                Return CType(Me("ServDatos7"),String)
            End Get
            Set
                Me("ServDatos7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VACIO")>  _
        Public Property ServDatos8() As String
            Get
                Return CType(Me("ServDatos8"),String)
            End Get
            Set
                Me("ServDatos8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VACIO")>  _
        Public Property ServDatos9() As String
            Get
                Return CType(Me("ServDatos9"),String)
            End Get
            Set
                Me("ServDatos9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property TipoEsquema() As Byte
            Get
                Return CType(Me("TipoEsquema"),Byte)
            End Get
            Set
                Me("TipoEsquema") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Zebra() As String
            Get
                Return CType(Me("Zebra"),String)
            End Get
            Set
                Me("Zebra") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Camara() As String
            Get
                Return CType(Me("Camara"),String)
            End Get
            Set
                Me("Camara") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Resolucion() As String
            Get
                Return CType(Me("Resolucion"),String)
            End Get
            Set
                Me("Resolucion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property CompresionImagen() As Integer
            Get
                Return CType(Me("CompresionImagen"),Integer)
            End Get
            Set
                Me("CompresionImagen") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("400")>
        Public Property TamanoMaxImagen() As Integer
            Get
                Return CType(Me("TamanoMaxImagen"), Integer)
            End Get
            Set
                Me("TamanoMaxImagen") = value
            End Set
        End Property


        '---------Coneccion a bases central---------- 
        <Global.System.Configuration.UserScopedSettingAttribute(),
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
 Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property CtrServer() As String
            Get
                Return CType(Me("CtrServer"), String)
            End Get
            Set
                Me("CtrServer") = Value
            End Set
        End Property


        <Global.System.Configuration.UserScopedSettingAttribute(),
    Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
    Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property CtrBase() As String
            Get
                Return CType(Me("CtrBase"), String)
            End Get
            Set
                Me("CtrBase") = Value
            End Set
        End Property



        <Global.System.Configuration.UserScopedSettingAttribute(),
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
 Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property CtrUsuario() As String
            Get
                Return CType(Me("CtrUsuario"), String)
            End Get
            Set
                Me("CtrUsuario") = Value
            End Set
        End Property



        <Global.System.Configuration.UserScopedSettingAttribute(),
    Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
    Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property CtrClave() As String
            Get
                Return CType(Me("CtrClave"), String)
            End Get
            Set
                Me("CtrClave") = Value
            End Set
        End Property

    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Modulo_Reclutamiento.My.MySettings
            Get
                Return Global.Modulo_Reclutamiento.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
